"""English analytical labels for the 231 normalized FGJ 2024 criminal offences.

Keys are actual ``delito`` values after accent normalization, not the broader
``categoria_delito`` labels. Preserve distinctions in the source descriptions;
these translations are analytical labels, not a replacement for the raw text.
"""

CRIME_TYPE_TRANSLATIONS = {
    "ABORTO": "Abortion",
    "ABUSO DE AUTORIDAD Y USO ILEGAL DE LA FUERZA PUBLICA": "Abuse of Authority and Unlawful Use of Public Force",
    "ABUSO DE CONFIANZA": "Breach of Trust / Embezzlement",
    "ABUSO SEXUAL": "Sexual Abuse",
    "ACOSO SEXUAL": "Sexual Harassment",
    "ACOSO SEXUAL AGRAVADO EN CONTRA DE MENORES": "Aggravated Sexual Harassment of Minors",
    "ALLANAMIENTO DE MORADA, DESPACHO, OFICINA O ESTABLECIMIENTO MERCANTIL": "Unlawful Entry into a Home, Office or Business",
    "AMENAZAS": "Threats",
    "ATAQUE A LAS VIAS DE COMUNICACION (DANO A VIAS O MEDIOS DE TRANSPORTE)": "Attack on Transport Routes (Damage to Routes or Vehicles)",
    "ATAQUE A LAS VIAS GENERALES DE COMUNICACION": "Attack on General Transport Routes",
    "BIGAMIA": "Bigamy",
    "CAMBIO DE USO DE SUELO": "Unlawful Land Use Change",
    "COBRANZA ILEGITIMA": "Unlawful Debt Collection",
    "COHECHO": "Bribery",
    "CONTAMINACION O RESIDUOS": "Pollution or Waste Offence",
    "CONTRA EL CUMPLIMIENTO DE LA OBLIGACION ALIMENTARIA": "Failure to Fulfil Maintenance Obligations",
    "CONTRA EL ESTADO CIVIL": "Offence against Civil Status",
    "CONTRA FUNCIONARIOS PUBLICOS": "Offence against Public Officials",
    "CONTRA LA INTIMIDAD SEXUAL": "Offence against Sexual Privacy",
    "CORRUPCION DE PERSONAS MENORES DE EDAD O PERSONAS QUE NO TENGAN CAPACIDAD PARA COMPRENDER EL SIGNIFICADO DEL HECHO O DE PERSONAS QUE NO TENGAN CAPACIDAD DE RESISTIR LA CONDUCTA": "Corruption of Minors or Persons Unable to Understand or Resist the Act",
    "DANO EN PROPIEDAD AJENA CULPOSA": "Negligent Damage to Another Person's Property",
    "DANO EN PROPIEDAD AJENA CULPOSA POR TRANSITO VEHICULAR A AUTOMOVIL": "Negligent Traffic Damage to an Automobile",
    "DANO EN PROPIEDAD AJENA CULPOSA POR TRANSITO VEHICULAR A BIENES INMUEBLES": "Negligent Traffic Damage to Real Property",
    "DANO EN PROPIEDAD AJENA CULPOSA POR TRANSITO VEHICULAR A VIAS DE COMUNICACION": "Negligent Traffic Damage to Transport Routes",
    "DANO EN PROPIEDAD AJENA INTENCIONAL": "Intentional Damage to Another Person's Property",
    "DANO EN PROPIEDAD AJENA INTENCIONAL A AUTOMOVIL": "Intentional Property Damage to Automobile",
    "DANO EN PROPIEDAD AJENA INTENCIONAL A BIENES INMUEBLES": "Intentional Damage to Real Property",
    "DANO EN PROPIEDAD AJENA INTENCIONAL A CASA HABITACION": "Intentional Damage to a Residence",
    "DANO EN PROPIEDAD AJENA INTENCIONAL A NEGOCIO": "Intentional Damage to a Business",
    "DANO EN PROPIEDAD AJENA INTENCIONAL A VIAS DE COMUNICACION": "Intentional Damage to Transport Routes",
    "DANO SUELO (ACTIVIDAD, INVASION O EXTRACCION)": "Soil Damage (Activity, Encroachment or Extraction)",
    "DELITOS AMBIENTALES": "Environmental Offences",
    "DELITOS DE ABOGADOS, PATRONOS, LITIGANTES Y ASESORES JURIDICOS": "Offences by Lawyers, Legal Representatives, Litigants and Legal Advisers",
    "DELITOS ELECTORALES": "Electoral Offences",
    "DESAPARICION FORZADA DE PERSONAS": "Enforced Disappearance",
    "DESOBEDENCIA DE PARTICULARES": "Disobedience by Private Individuals",
    "DESOBEDIENCIA Y RESISTENCIA DE PARTICULARES": "Disobedience and Resistance by Private Individuals",
    "DESPOJO": "Dispossession / Squatting",
    "DISCRIMINACION": "Discrimination",
    "DISPAROS DE ARMA DE FUEGO": "Discharge of a Firearm",
    "EJERCICIO ABUSIVO DE FUNCIONES": "Abusive Exercise of Public Functions",
    "EJERCICIO ILEGAL Y ABANDONO DEL SERVICIO PUBLICO": "Unlawful Exercise and Abandonment of Public Service",
    "EJERCICIO INDEBIDO DEL PROPIO DER.": "Unlawful Exercise of One's Own Rights",
    "ENCUBRIMIENTO": "Concealment of an Offence",
    "ENCUBRIMIENTO POR FAVORECIMIENTO": "Concealment by Assisting an Offender",
    "ENRIQUECIMIENTO ILICITO": "Illicit Enrichment",
    "ESTUPRO": "Sexual Intercourse with a Minor Obtained by Deception",
    "EVASION DE PRESOS": "Prisoner Escape",
    "EXPLOTACION LABORAL DE MENORES, PERSONAS CON DISCAPACIDAD FISICA O MENTAL Y ADULTOS MAYORES": "Labour Exploitation of Minors, Persons with Disabilities and Older Adults",
    "EXPOSICION DE MENORES": "Child Exposure to Danger",
    "EXTORSION": "Extortion",
    "FABRICACION, COMERCIALIZACION Y USO INDEBIDO DE INSIGNIAS Y UNIFORMES": "Unlawful Manufacture, Sale and Use of Insignia and Uniforms",
    "FALSEDAD ANTE AUTORIDADES": "False Statements to Authorities",
    "FALSIFICACION DE SELLOS, MARCAS, LLAVES, CUNOS, TROQUELES, CONTRASENAS Y OTROS": "Forgery of Seals, Marks, Keys, Stamps, Dies, Passwords and Other Items",
    "FALSIFICACION O ALTERACION Y USO INDEBIDO DE DOCUMENTOS": "Forgery, Alteration and Misuse of Documents",
    "FEMINICIDIO": "Femicide",
    "FEMINICIDIO POR ARMA BLANCA": "Femicide with a Bladed Weapon",
    "FEMINICIDIO POR DISPARO DE ARMA DE FUEGO": "Femicide by Firearm Discharge",
    "FEMINICIDIO POR GOLPES": "Femicide by Beating",
    "FRAUDE": "Fraud",
    "GESTION AMBIENTAL": "Environmental Management Offence",
    "HOMICIDIO CULPOSO CON EXCLUYENTES DE RESPONSABILIDAD": "Negligent Homicide with Grounds Excluding Liability",
    "HOMICIDIO CULPOSO FUERA DEL D.F (ATROPELLADO)": "Negligent Homicide outside Mexico City (Pedestrian Struck)",
    "HOMICIDIO CULPOSO FUERA DEL D.F (COLISION)": "Negligent Homicide outside Mexico City (Collision)",
    "HOMICIDIO CULPOSO POR ARMA DE FUEGO": "Negligent Homicide with a Firearm",
    "HOMICIDIO CULPOSO POR TRANSITO VEHICULAR": "Negligent Homicide in Traffic",
    "HOMICIDIO CULPOSO POR TRANSITO VEHICULAR (ATROPELLADO)": "Negligent Homicide in Traffic (Pedestrian Struck)",
    "HOMICIDIO CULPOSO POR TRANSITO VEHICULAR (CAIDA)": "Negligent Homicide in Traffic (Fall)",
    "HOMICIDIO CULPOSO POR TRANSITO VEHICULAR (COLISION)": "Negligent Homicide in Traffic (Collision)",
    "HOMICIDIO POR ARMA BLANCA": "Homicide with a Bladed Weapon",
    "HOMICIDIO POR ARMA DE FUEGO": "Homicide with a Firearm",
    "HOMICIDIO POR GOLPES": "Homicide by Beating",
    "HOMICIDIOS INTENCIONALES (OTROS)": "Intentional Homicide (Other)",
    "INHUMACION, EXHUMACION Y RESPETO A LOS CADAVERES O RESTOS HUMANOS": "Offence Involving Burial, Exhumation or Respect for Human Remains",
    "INTIMIDACION": "Intimidation",
    "LA ADMINISTRACION DE JUSTICIA": "Offence against the Administration of Justice",
    "LENOCINIO": "Procuring Prostitution",
    "LESIONES CULPOSAS": "Negligent Injury",
    "LESIONES CULPOSAS ACCIDENTE LABORAL": "Negligent Injury in a Workplace Accident",
    "LESIONES CULPOSAS CON EXCLUYENTES DE RESPONSABILIDAD": "Negligent Injury with Grounds Excluding Liability",
    "LESIONES CULPOSAS POR CAIDA": "Negligent Injury from a Fall",
    "LESIONES CULPOSAS POR CAIDA DE VEHICULO EN MOVIMIENTO": "Negligent Injury from Falling off a Moving Vehicle",
    "LESIONES CULPOSAS POR QUEMADURAS": "Negligent Injury from Burns",
    "LESIONES CULPOSAS POR TRANSITO VEHICULAR": "Negligent Injury in Traffic",
    "LESIONES CULPOSAS POR TRANSITO VEHICULAR EN COLISION": "Negligent Injury in a Traffic Collision",
    "LESIONES DOLOSAS POR QUEMADURAS": "Intentional Injury by Burning",
    "LESIONES INTENCIONALES": "Intentional Injury",
    "LESIONES INTENCIONALES POR ARMA BLANCA": "Intentional Injury with a Bladed Weapon",
    "LESIONES INTENCIONALES POR ARMA DE FUEGO": "Intentional Injury with a Firearm",
    "LESIONES INTENCIONALES POR GOLPES": "Intentional Assault and Battery",
    "MALTRATO ANIMAL": "Animal Cruelty",
    "NARCOMENUDEO POSESION CON FINES DE VENTA, COMERCIO Y SUMINISTRO": "Drug Possession with Intent to Distribute",
    "NARCOMENUDEO POSESION SIMPLE": "Drug Possession (Simple)",
    "NEGACION DEL SERVICIO PUBLICO": "Denial of Public Service",
    "OMISION DE AUXILIO O DE CUIDADO": "Failure to Provide Aid or Care",
    "OPERACIONES CON RECURSOS DE PROCEDENCIA ILICITA": "Transactions with Illicit Proceeds",
    "OPOSICION A QUE SE EJECUTE ALGUNA OBRA O TRABAJO PUBLICOS": "Obstruction of Public Works",
    "PANDILLA, ASOCIACION DELICTUOSA Y DELINCUENCIA ORGANIZADA": "Gang Activity, Criminal Association and Organized Crime",
    "PECULADO": "Embezzlement of Public Funds",
    "PELIGRO DE CONTAGIO": "Exposure to Infection",
    "PERSONAS EXTRAVIADAS Y AUSENTES": "Missing and Absent Persons",
    "PLAGIO O SECUESTRO": "Kidnapping",
    "PORNOGRAFIA": "Pornography Offence",
    "PORTACION DE ARMA DE FUEGO": "Unlawful Carrying of a Firearm",
    "PORTACION, FABRICACION E IMPORTACION DE OBJETOS APTOS PARA AGREDIR": "Carrying, Manufacture and Import of Objects Suitable for Assault",
    "PRIV. ILEGAL DE LA LIB. Y ROBO DE VEHICULO": "Unlawful Deprivation of Liberty and Vehicle Theft",
    "PRIVACION DE LA LIBERTAD PERSONAL": "Deprivation of Personal Liberty",
    "PRIVACION DE LA LIBERTAD PERSONAL (REALIZAR ACTO SEXUAL)": "Deprivation of Personal Liberty to Perform a Sexual Act",
    "PRODUCCION, IMPRESION, ENAJENACION, DISTRIBUCION, ALTERACION O FALSIFICACION DE TITULOS AL PORTADOR, DOCUMENTOS DE CREDITO PUBLICOS O VALES DE CANJE": "Production, Printing, Sale, Distribution, Alteration or Forgery of Bearer Securities, Public Credit Documents or Vouchers",
    "QUEBRANTAMIENTO DE SELLOS": "Breaking Official Seals",
    "REGULACION URBANA": "Urban Regulation Offence",
    "RESPONSABILIDAD PROFESIONAL Y TECNICA": "Professional and Technical Liability Offence",
    "RETENCION DE MENORES": "Unlawful Retention of Minors",
    "REVELACION DE SECRETOS": "Disclosure of Secrets",
    "ROBO A CASA HABITACION CON VIOLENCIA": "Residential Burglary with Violence",
    "ROBO A CASA HABITACION SIN VIOLENCIA": "Residential Burglary without Violence",
    "ROBO A CASA HABITACION Y VEHICULO CON VIOLENCIA": "Residential Burglary and Vehicle Theft with Violence",
    "ROBO A CASA HABITACION Y VEHICULO SIN VIOLENCIA": "Residential Burglary and Vehicle Theft without Violence",
    "ROBO A LOCALES SEMIFIJOS (PUESTOS DE ALIMENTOS,BEBIDAS, ENSERES, PERIODICOS,LOTERIA, OTROS)": "Theft from Semi-Fixed Stalls (Food, Drinks, Household Goods, Newspapers, Lottery and Other)",
    "ROBO A NEGOCIO CON VIOLENCIA": "Robbery at Business with Violence",
    "ROBO A NEGOCIO CON VIOLENCIA POR FARDEROS (TIENDAS DE AUTOSERVICIO)": "Shoplifting with Violence (Self-Service Stores)",
    "ROBO A NEGOCIO CON VIOLENCIA POR FARDEROS (TIENDAS DE CONVENIENCIA)": "Shoplifting with Violence (Convenience Stores)",
    "ROBO A NEGOCIO SIN VIOLENCIA": "Business Theft without Violence",
    "ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS": "Shoplifting at Commercial Business",
    "ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS (TIENDAS DE AUTOSERVICIO)": "Shoplifting at Commercial Business (Self-Service Stores)",
    "ROBO A NEGOCIO SIN VIOLENCIA POR FARDEROS (TIENDAS DE CONVENIENCIA)": "Shoplifting at Commercial Business (Convenience Stores)",
    "ROBO A NEGOCIO Y VEHICULO CON VIOLENCIA": "Business Robbery and Vehicle Theft with Violence",
    "ROBO A NEGOCIO Y VEHICULO SIN VIOLENCIA": "Business and Vehicle Theft without Violence",
    "ROBO A OFICINA PUBLICA CON VIOLENCIA": "Public Office Robbery with Violence",
    "ROBO A OFICINA PUBLICA SIN VIOLENCIA": "Public Office Theft without Violence",
    "ROBO A PASAJERO / CONDUCTOR DE VEHICULO CON VIOLENCIA": "Robbery of a Vehicle Passenger or Driver with Violence",
    "ROBO A PASAJERO A BORDO DE METRO CON VIOLENCIA": "Robbery of a Metro Passenger with Violence",
    "ROBO A PASAJERO A BORDO DE METRO SIN VIOLENCIA": "Theft from a Metro Passenger without Violence",
    "ROBO A PASAJERO A BORDO DE METROBUS CON VIOLENCIA": "Robbery of a Metrobus Passenger with Violence",
    "ROBO A PASAJERO A BORDO DE METROBUS SIN VIOLENCIA": "Theft from a Metrobus Passenger without Violence",
    "ROBO A PASAJERO A BORDO DE PESERO COLECTIVO CON VIOLENCIA": "Robbery of a Shared Minibus Passenger with Violence",
    "ROBO A PASAJERO A BORDO DE PESERO COLECTIVO SIN VIOLENCIA": "Theft from a Shared Minibus Passenger without Violence",
    "ROBO A PASAJERO A BORDO DE TRANSPORTE PUBLICO CON VIOLENCIA": "Robbery of a Public Transport Passenger with Violence",
    "ROBO A PASAJERO A BORDO DE TRANSPORTE PUBLICO SIN VIOLENCIA": "Theft from a Public Transport Passenger without Violence",
    "ROBO A PASAJERO EN AUTOBUS FORANEO CON VIOLENCIA": "Robbery of an Intercity Bus Passenger with Violence",
    "ROBO A PASAJERO EN AUTOBUS FORANEO SIN VIOLENCIA": "Theft from an Intercity Bus Passenger without Violence",
    "ROBO A PASAJERO EN ECOBUS CON VIOLENCIA": "Robbery of an Ecobus Passenger with Violence",
    "ROBO A PASAJERO EN ECOBUS SIN VIOLENCIA": "Theft from an Ecobus Passenger without Violence",
    "ROBO A PASAJERO EN RTP CON VIOLENCIA": "Robbery of an RTP Bus Passenger with Violence",
    "ROBO A PASAJERO EN RTP SIN VIOLENCIA": "Theft from an RTP Bus Passenger without Violence",
    "ROBO A PASAJERO EN TREN LIGERO CON VIOLENCIA": "Robbery of a Light Rail Passenger with Violence",
    "ROBO A PASAJERO EN TREN LIGERO SIN VIOLENCIA": "Theft from a Light Rail Passenger without Violence",
    "ROBO A PASAJERO EN TREN SUBURBANO CON VIOLENCIA": "Robbery of a Suburban Train Passenger with Violence",
    "ROBO A PASAJERO EN TREN SUBURBANO SIN VIOLENCIA": "Theft from a Suburban Train Passenger without Violence",
    "ROBO A PASAJERO EN TROLEBUS CON VIOLENCIA": "Robbery of a Trolleybus Passenger with Violence",
    "ROBO A PASAJERO EN TROLEBUS SIN VIOLENCIA": "Theft from a Trolleybus Passenger without Violence",
    "ROBO A REPARTIDOR CON VIOLENCIA": "Robbery of Delivery Personnel with Violence",
    "ROBO A REPARTIDOR SIN VIOLENCIA": "Theft from Delivery Personnel without Violence",
    "ROBO A REPARTIDOR Y VEHICULO CON VIOLENCIA": "Robbery of Delivery Personnel and Vehicle with Violence",
    "ROBO A REPARTIDOR Y VEHICULO SIN VIOLENCIA": "Theft from Delivery Personnel and Vehicle without Violence",
    "ROBO A SUCURSAL BANCARIA SIN VIOLENCIA": "Bank Branch Theft without Violence",
    "ROBO A TRANSEUNTE A BORDO DE TAXI PUBLICO Y PRIVADO CON VIOLENCIA": "Robbery of a Public or Private Taxi Passenger with Violence",
    "ROBO A TRANSEUNTE A BORDO DE TAXI PUBLICO Y PRIVADO SIN VIOLENCIA": "Theft from a Public or Private Taxi Passenger without Violence",
    "ROBO A TRANSEUNTE CONDUCTOR DE TAXI PUBLICO Y PRIVADO CON VIOLENCIA": "Robbery of a Public or Private Taxi Driver with Violence",
    "ROBO A TRANSEUNTE DE CELULAR CON VIOLENCIA": "Cell Phone Robbery with Violence",
    "ROBO A TRANSEUNTE DE CELULAR SIN VIOLENCIA": "Cell Phone Theft without Violence",
    "ROBO A TRANSEUNTE EN HOTEL CON VIOLENCIA": "Robbery of a Person at a Hotel with Violence",
    "ROBO A TRANSEUNTE EN NEGOCIO CON VIOLENCIA": "Robbery of a Person at a Business with Violence",
    "ROBO A TRANSEUNTE EN PARQUES Y MERCADOS CON VIOLENCIA": "Robbery in Parks or Markets with Violence",
    "ROBO A TRANSEUNTE EN RESTAURANT CON VIOLENCIA": "Robbery of a Person at a Restaurant with Violence",
    "ROBO A TRANSEUNTE EN VIA PUBLICA CON VIOLENCIA": "Robbery on Public Road with Violence",
    "ROBO A TRANSEUNTE EN VIA PUBLICA SIN VIOLENCIA": "Theft on Public Road without Violence",
    "ROBO A TRANSEUNTE SALIENDO DEL BANCO CON VIOLENCIA": "Robbery of a Person Leaving a Bank with Violence",
    "ROBO A TRANSEUNTE SALIENDO DEL CAJERO CON VIOLENCIA": "Robbery of a Person Leaving an ATM with Violence",
    "ROBO A TRANSPORTISTA Y VEHICULO PESADO CON VIOLENCIA": "Robbery of a Freight Carrier and Heavy Vehicle with Violence",
    "ROBO A TRANSPORTISTA Y VEHICULO PESADO SIN VIOLENCIA": "Theft from a Freight Carrier and Heavy Vehicle without Violence",
    "ROBO DE ACCESORIOS DE AUTO": "Theft of Auto Parts and Accessories",
    "ROBO DE ALHAJAS": "Jewellery Theft",
    "ROBO DE ANIMALES": "Animal Theft",
    "ROBO DE ARMA": "Weapon Theft",
    "ROBO DE CONTENEDORES DE TRAILERS S/V": "Theft of Trailer Containers without Violence",
    "ROBO DE DINERO": "Theft of Money",
    "ROBO DE DOCUMENTOS": "Document Theft",
    "ROBO DE FLUIDOS": "Theft of Fluids",
    "ROBO DE MAQUINARIA CON VIOLENCIA": "Machinery Theft with Violence",
    "ROBO DE MERCANCIA A TRANSPORTISTA C/V": "Theft of Goods from a Freight Carrier with Violence",
    "ROBO DE MERCANCIA EN CONTENEDEROS EN AREAS FEDERALES": "Theft of Goods from Containers in Federal Areas",
    "ROBO DE MOTOCICLETA CON VIOLENCIA": "Motorcycle Theft with Violence",
    "ROBO DE MOTOCICLETA SIN VIOLENCIA": "Motorcycle Theft without Violence",
    "ROBO DE OBJETOS": "Theft of Personal Property",
    "ROBO DE OBJETOS A ESCUELA": "Theft of Property from a School",
    "ROBO DE OBJETOS DEL INTERIOR DE UN VEHICULO": "Theft from Vehicle Interior",
    "ROBO DE PLACA DE AUTOMOVIL": "Theft of License Plate",
    "ROBO DE VEHICULO DE PEDALES": "Pedal Vehicle Theft",
    "ROBO DE VEHICULO DE SERVICIO DE TRANSPORTE CON VIOLENCIA": "Transport Service Vehicle Theft with Violence",
    "ROBO DE VEHICULO DE SERVICIO DE TRANSPORTE SIN VIOLENCIA": "Transport Service Vehicle Theft without Violence",
    "ROBO DE VEHICULO DE SERVICIO OFICIAL CON VIOLENCIA": "Official Service Vehicle Theft with Violence",
    "ROBO DE VEHICULO DE SERVICIO OFICIAL SIN VIOLENCIA": "Official Service Vehicle Theft without Violence",
    "ROBO DE VEHICULO DE SERVICIO PARTICULAR CON VIOLENCIA": "Private Vehicle Theft with Violence",
    "ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VIOLENCIA": "Private Vehicle Theft without Violence",
    "ROBO DE VEHICULO DE SERVICIO PUBLICO CON VIOLENCIA": "Public Service Vehicle Theft with Violence",
    "ROBO DE VEHICULO DE SERVICIO PUBLICO SIN VIOLENCIA": "Public Service Vehicle Theft without Violence",
    "ROBO DE VEHICULO ELECTRICO MOTOPATIN": "Electric Scooter Theft",
    "ROBO DE VEHICULO EN PENSION, TALLER Y AGENCIAS S/V": "Vehicle Theft at Parking Facilities, Workshops or Dealerships without Violence",
    "ROBO DURANTE TRASLADO DE VALORES (NOMINA) CON VIOLENCIA": "Theft during Cash Transport (Payroll) with Violence",
    "ROBO DURANTE TRASLADO DE VALORES (NOMINA) SIN VIOLENCIA": "Theft during Cash Transport (Payroll) without Violence",
    "ROBO EN EVENTOS MASIVOS (DEPORTIVOS, CULTURALES, RELIGIOSOS Y ARTISTICOS) S/V": "Theft at Mass Events (Sports, Cultural, Religious and Artistic) without Violence",
    "ROBO S/V DENTRO DE NEGOCIOS, AUTOSERVICIOS, CONVENIENCIA": "Theft inside Businesses, Self-Service and Convenience Stores without Violence",
    "SABOTAJE": "Sabotage",
    "SECUESTRO EXPRESS (PARA COMETER ROBO O EXTORSION)": "Express Kidnapping for Robbery or Extortion",
    "SUSTRACCION DE MENORES": "Child Abduction",
    "TALA": "Illegal Logging",
    "TENTATIVA DE EXTORSION": "Attempted Extortion",
    "TENTATIVA DE FEMINICIDIO": "Attempted Femicide",
    "TENTATIVA DE FRAUDE": "Attempted Fraud",
    "TENTATIVA DE HOMICIDIO": "Attempted Homicide",
    "TENTATIVA DE ROBO": "Attempted Theft or Robbery",
    "TENTATIVA DE ROBO DE VEHICULO": "Attempted Vehicle Theft",
    "TENTATIVA DE SUICIDIO": "Attempted Suicide",
    "TENTATIVA DE VIOLACION": "Attempted Rape",
    "TORTURA": "Torture",
    "TRAFICO DE INFLUENCIA": "Influence Peddling",
    "TRATA DE PERSONAS": "Human Trafficking",
    "USO DE DOCUMENTO FALSO": "Use of a Forged Document",
    "USO INDEBIDO DE ATRIBUCIONES Y FACULTADES": "Misuse of Official Powers and Authority",
    "USURPACION DE FUNCIONES PUBLICAS": "Usurpation of Public Functions",
    "USURPACION DE IDENTIDAD": "Identity Theft",
    "USURPACION DE PROFESION": "Unlawful Practice of a Profession",
    "VARIACION DE NOMBRE O DOMICILIO": "Misrepresentation of Name or Address",
    "VIOLACION": "Rape",
    "VIOLACION DE CORRESPONDENCIA": "Violation of Correspondence Privacy",
    "VIOLACION EQUIPARADA": "Offence Legally Equivalent to Rape",
    "VIOLACION EQUIPARADA POR CONOCIDO": "Offence Legally Equivalent to Rape by an Acquaintance",
    "VIOLACION TUMULTUARIA": "Gang Rape",
    "VIOLACION TUMULTUARIA EQUIPARADA": "Group Offence Legally Equivalent to Rape",
    "VIOLENCIA FAMILIAR": "Family Violence",
}
